# Generated by Django 5.1.3 on 2024-11-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
