# Generated by Django 5.1.3 on 2024-11-29 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_post_images_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_replies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
