# Generated by Django 5.1.3 on 2024-11-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_comment_likes_reply_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="short_name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
